#ACR介绍
Remark: |
  镰刀ACR，日随场景经过测试，高难绝欧已过本，其他环境欢迎使用并提出改进建议。
  2025/10/22: 修复回退Hotkey，修改距离判断方式。
#支持的职业
SupportJobs:
  - 钐镰客
#支持链接
SupportUrl: https://github.com/ElliotZ/AE3-ACR
#问题反馈链接
ReportUrl: https://discord.com/channels/1191648233454313482/1403581424208183429
#是否国际服版本
EnVersion: false